export const TreamentsOption = [
  { label: "Medication", value: 1 },
  { label: "Physical Therapy", value: 2 },
  { label: "Cognitive Behavioral Therapy (CBT)", value: 3 },
  { label: "Surgery", value: 4 },
  { label: "Acupuncture", value: 5 },
  { label: "Massage Therapy", value: 6 },
  { label: "Chiropractic Care", value: 7 },
  { label: "Occupational Therapy", value: 8 },
  { label: "Psychotherapy", value: 9 },
  { label: "Home Remedies", value: 10 },
  { label: "Alternative Medicine", value: 11 },
  { label: "Rehabilitation Programs", value: 12 },
  { label: "Diet and Nutrition Counseling", value: 13 },
  { label: "Stress Management Techniques", value: 14 },
  { label: "Electrotherapy", value: 15 },
  { label: "Respiratory Therapy", value: 16 },
  { label: "Speech Therapy", value: 17 },
  { label: "Hydrotherapy", value: 18 },
  { label: "Inpatient Rehabilitation", value: 19 },
  { label: "Behavioral Therapy", value: 20 },
];

export const MedicationsOption = [
  { label: "Aspirin", value: 1 },
  { label: "Ibuprofen", value: 2 },
  { label: "Acetaminophen", value: 3 },
  { label: "Amoxicillin", value: 4 },
  { label: "Lisinopril", value: 5 },
  { label: "Metformin", value: 6 },
  { label: "Levothyroxine", value: 7 },
  { label: "Atorvastatin", value: 8 },
  { label: "Omeprazole", value: 9 },
  { label: "Albuterol", value: 10 },
  { label: "Prednisone", value: 11 },
  { label: "Hydrochlorothiazide", value: 12 },
  { label: "Losartan", value: 13 },
  { label: "Simvastatin", value: 14 },
  { label: "Citalopram", value: 15 },
  { label: "Sertraline", value: 16 },
  { label: "Fluoxetine", value: 17 },
  { label: "Warfarin", value: 18 },
  { label: "Diazepam", value: 19 },
  { label: "Escitalopram", value: 20 },
];
